### ISSUE TITLE
Get Basler camera code

### ISSUE THREAD

**Issue by paulmatthis** [freemocap/bs#3]
Get Basler camera code
      - integrate Basler support into `skellycam`

**Comment by jonmatthis** [comment]
We can reliably record synchronized videos from (at least) the 4 IR cameras at ~50fps and 2048x2048 resolution 

Sync seems very good, frame durations at least within 0.1ms of expectation)

**Comment by jonmatthis** [comment]
Marking done for now, next steps will involve more robust and flexible recording methods and integration of RGB top cam, pupil cams, etc

**Comment by jonmatthis** [comment]
Sample timestamp plots from 60-frame recording from 4 IR cameras @ 1024x1024 resolution 

![Image](https://github.com/user-attachments/assets/be07c3bf-462e-47c3-9ad7-d542ebbf414d)
